test1:
	python test_bug.py 1 > result_test1.log 2>/dev/null

test2:
	python test_bug.py 2 > result_test2.log 2>/dev/null

test3:
	python test_bug.py 3 > result_test3.log 2>/dev/null

test_smart1:
	python test_bug_smart.py 1 > result_test_smart1.log 2>/dev/null

test_smart2:
	python test_bug_smart.py 2 > result_test_smart2.log 2>/dev/null

test_smart3:
	python test_bug_smart.py 3 > result_test_smart3.log 2>/dev/null

clean:
	rm -rf server/zoobar/db
