test1:
	python test_bug.py 1

test2:
	python test_bug.py 2

test3:
	python test_bug.py 3

test_smart1:
	python test_bug_smart.py 1

test_smart2:
	python test_bug_smart.py 2

test_smart3:
	python test_bug_smart.py 3

clean:
	rm -rf server/zoobar/db
